name: Generate and Publish Swagger JSON

on:
  push:
    branches:
      - main

jobs:
  generate-swagger:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Generate Swagger JSON
      - name: Generate Swagger JSON
        run: |
          NODE_ENV=example npx ts-node -r tsconfig-paths/register src/scripts/swagger.ts

      # Step 5: Push Swagger JSON to a separate repository
      - name: Push Swagger JSON
        run: |
          git clone https://github.com/<your-username>/<your-swagger-repo>.git swagger-repo
          cp swagger.json swagger-repo/
          cd swagger-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add swagger.json
          git commit -m "Update Swagger JSON"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
